base_url = "https://huml.io/alpha-preview"

generate_feeds = true
generate_sitemap = true
feed_filenames = ["rss.xml"]

[markdown]
highlight_code = true
highlight_theme = "two-dark"
extra_syntaxes_and_themes = ["syntaxes"]

[extra]
default_title = "HUML :: Human-oriented Markup Language"
